/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomWaterRouteImport } from './routes/custom-water'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as BranchesSlugRouteImport } from './routes/branches.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ServiceAreasSlugRouteImport } from './routes/service-areas.$slug'
import { Route as ApiMediaDeleteRouteImport } from './routes/api.media.delete'
import { Route as ApiMediaUploadRouteImport } from './routes/api.media.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomWaterRoute = CustomWaterRouteImport.update({
  id: '/custom-water',
  path: '/custom-water',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const BranchesSlugRoute = BranchesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BranchesRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocationsRoute,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasSlugRoute = ServiceAreasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const ApiMediaDeleteRoute = ApiMediaDeleteRouteImport.update({
  id: '/api/media/delete',
  path: '/api/media/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/branches': typeof BranchesRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-water': typeof CustomWaterRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/locations': typeof LocationsRouteWithChildren
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/media/$': typeof MediaSplatRoute
  '/product/$id': typeof ProductIdRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/api/media/delete': typeof ApiMediaDeleteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/branches': typeof BranchesRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-water': typeof CustomWaterRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/locations': typeof LocationsRouteWithChildren
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/media/$': typeof MediaSplatRoute
  '/product/$id': typeof ProductIdRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/api/media/delete': typeof ApiMediaDeleteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/branches': typeof BranchesRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-water': typeof CustomWaterRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/locations': typeof LocationsRouteWithChildren
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/media/$': typeof MediaSplatRoute
  '/product/$id': typeof ProductIdRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/api/media/delete': typeof ApiMediaDeleteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/branches'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom-water'
    | '/faq'
    | '/gallery'
    | '/locations'
    | '/order-success'
    | '/privacy'
    | '/products'
    | '/service-areas'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/login'
    | '/branches/$slug'
    | '/category/$slug'
    | '/locations/$slug'
    | '/media/$'
    | '/product/$id'
    | '/service-areas/$slug'
    | '/api/media/delete'
    | '/api/media/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/branches'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom-water'
    | '/faq'
    | '/gallery'
    | '/locations'
    | '/order-success'
    | '/privacy'
    | '/products'
    | '/service-areas'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/login'
    | '/branches/$slug'
    | '/category/$slug'
    | '/locations/$slug'
    | '/media/$'
    | '/product/$id'
    | '/service-areas/$slug'
    | '/api/media/delete'
    | '/api/media/upload'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/branches'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom-water'
    | '/faq'
    | '/gallery'
    | '/locations'
    | '/order-success'
    | '/privacy'
    | '/products'
    | '/service-areas'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/login'
    | '/branches/$slug'
    | '/category/$slug'
    | '/locations/$slug'
    | '/media/$'
    | '/product/$id'
    | '/service-areas/$slug'
    | '/api/media/delete'
    | '/api/media/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BranchesRoute: typeof BranchesRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomWaterRoute: typeof CustomWaterRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  LocationsRoute: typeof LocationsRouteWithChildren
  OrderSuccessRoute: typeof OrderSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  ServiceAreasRoute: typeof ServiceAreasRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  MediaSplatRoute: typeof MediaSplatRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiMediaDeleteRoute: typeof ApiMediaDeleteRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-water': {
      id: '/custom-water'
      path: '/custom-water'
      fullPath: '/custom-water'
      preLoaderRoute: typeof CustomWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/branches/$slug': {
      id: '/branches/$slug'
      path: '/$slug'
      fullPath: '/branches/$slug'
      preLoaderRoute: typeof BranchesSlugRouteImport
      parentRoute: typeof BranchesRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$slug': {
      id: '/service-areas/$slug'
      path: '/$slug'
      fullPath: '/service-areas/$slug'
      preLoaderRoute: typeof ServiceAreasSlugRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/api/media/delete': {
      id: '/api/media/delete'
      path: '/api/media/delete'
      fullPath: '/api/media/delete'
      preLoaderRoute: typeof ApiMediaDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BranchesRouteChildren {
  BranchesSlugRoute: typeof BranchesSlugRoute
}

const BranchesRouteChildren: BranchesRouteChildren = {
  BranchesSlugRoute: BranchesSlugRoute,
}

const BranchesRouteWithChildren = BranchesRoute._addFileChildren(
  BranchesRouteChildren,
)

interface LocationsRouteChildren {
  LocationsSlugRoute: typeof LocationsSlugRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsSlugRoute: LocationsSlugRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

interface ServiceAreasRouteChildren {
  ServiceAreasSlugRoute: typeof ServiceAreasSlugRoute
}

const ServiceAreasRouteChildren: ServiceAreasRouteChildren = {
  ServiceAreasSlugRoute: ServiceAreasSlugRoute,
}

const ServiceAreasRouteWithChildren = ServiceAreasRoute._addFileChildren(
  ServiceAreasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BranchesRoute: BranchesRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomWaterRoute: CustomWaterRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  LocationsRoute: LocationsRouteWithChildren,
  OrderSuccessRoute: OrderSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  ServiceAreasRoute: ServiceAreasRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  MediaSplatRoute: MediaSplatRoute,
  ProductIdRoute: ProductIdRoute,
  ApiMediaDeleteRoute: ApiMediaDeleteRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
